# Utiliser une image Node.js + yt-dlp
FROM python:3.11

# Installer yt-dlp et ffmpeg
RUN pip install yt-dlp && apt-get update && apt-get install -y ffmpeg

# Installer Express et les dépendances
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Lancer le serveur Node.js
CMD ["node", "index.js"]
